### ISSUE TITLE
Crashes under Windows due to pointer-to-long cast

### ISSUE THREAD

**Issue by bertholet** [ataiya/kdtree#5]
I consistently got system crashes on my system with Matlab 2016b,windows10, visual studio 2013 c++. The problem is that longs have only 4 Byte in VS and casting pointers to long breaks them. Could fix it by replacing long by intptr_t,

**Comment by taiya** [comment]
feel free to create a pull request!

**Comment by taiya** [comment]
Thanks for your pull request!

**Comment by bertholet** [comment]
No worries, and thank you for the handy implementation(;
